In [1]:
!pip install transformers

     |████████████████████████████████| 645kB 2.6MB/s 
     |████████████████████████████████| 1.1MB 9.7MB/s 
     |████████████████████████████████| 890kB 19.7MB/s 
     |████████████████████████████████| 3.8MB 21.5MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=b2d2480244d92c4f79ea51374fbdf96e323ab28974191622d8f37ad12c268236
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [2]:
!pip install tensorboardx

     |████████████████████████████████| 204kB 2.7MB/s 


In [3]:
!pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 127.2MB 76kB/s 
     |████████████████████████████████| 5.4MB 40.2MB/s 
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101
  Found existing installation: torchvision 0.6.0+cu101
    Uninstalling torchvision-0.6.0+cu101:
      Successfully uninstalled torchvision-0.6.0+cu101


In [4]:
!pip install simpletransformers

     |████████████████████████████████| 194kB 2.7MB/s 
  Created wheel for seqeval: filename=seqeval-0.0.12-cp36-none-any.whl size=7424 sha256=1a8b510ee696460d6d52e4b9c7ce3e5e6fa1f3369bb77fd27e23449f5f4aba94
  Stored in directory: /root/.cache/pip/wheels/4f/32/0a/df3b340a82583566975377d65e724895b3fad101a3fb729f68
Successfully built seqeval


In [0]:
from simpletransformers.classification import MultiLabelClassificationModel
import pandas as pd
import logging

In [0]:
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

In [0]:
import os
import collections
import pandas as pd

In [8]:
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [9]:
data=pd.read_csv("/content/drive/My Drive/data/questions.csv",usecols=[3,5,6]) 
data=data[:5000]
print(data['Problem Statement'].iloc[0])

if len(str(data['Problem Statement']).split(".",1))>1:
  data['Problem Statement']=data['Problem Statement'].str.split(".",1).str[1]


All submissions for this problem are available. Read problems statements in  Mandarin Chinese  and  Russian.
Chef Ciel is playing a game with one of her colleagues.
 In this game, there are k piles of numbers. There are ni numbers in ith pile. In each move, player has to select a pile and finally a number from that pile. After that, all the numbers which are greater than or equal to chosen number will be removed from that pile. Players take turn alternatively. Player who is unable to move loses the game. 
Chef Ciel always make first move. But before making her move, she must choose either EVEN or ODD. If she chooses even then each time she selects a number it must be even and her opponent must select odd number in his/her turn. And vice versa for the other case. 
Please help Chef Ciel to make her choice. If neither choice can make her win game, print DON'T PLAY otherwise EVEN or ODD depending on which choice she should make to win game. If you think then you will understand BOTH can n

In [10]:
data['prob_sol'] = data['Problem Statement'] +' '+ data['Solution']
data['prob_sol']=data['prob_sol'].str.lower()
data.head()
print(data['Problem Statement'].iloc[0])

INFO:numexpr.utils:NumExpr defaulting to 2 threads.


 Read problems statements in  Mandarin Chinese  and  Russian.
Chef Ciel is playing a game with one of her colleagues.
 In this game, there are k piles of numbers. There are ni numbers in ith pile. In each move, player has to select a pile and finally a number from that pile. After that, all the numbers which are greater than or equal to chosen number will be removed from that pile. Players take turn alternatively. Player who is unable to move loses the game. 
Chef Ciel always make first move. But before making her move, she must choose either EVEN or ODD. If she chooses even then each time she selects a number it must be even and her opponent must select odd number in his/her turn. And vice versa for the other case. 
Please help Chef Ciel to make her choice. If neither choice can make her win game, print DON'T PLAY otherwise EVEN or ODD depending on which choice she should make to win game. If you think then you will understand BOTH can not be answer.
Assume that both players play inte

In [11]:
data.head()
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop = stopwords.words('english')
# data['Problem Statement'].apply(lambda x: [item for item in x if item not in stop])
# print("done1")
# data['Solution'].apply(lambda x: [item for item in x if item not in stop])
# print("done2")
data['prob_sol'].apply(lambda x: [item for item in x if item not in stop])
print("done3")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
done3


In [0]:
unique_labels=data.tags.unique()
num=len(unique_labels)

In [0]:
from simpletransformers.classification import MultiLabelClassificationModel
import pandas as pd

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data["prob_sol"].values, data["tags"].values, test_size=0.2, random_state=42)

In [15]:
model = MultiLabelClassificationModel(
    "bert",
    "bert-base-cased",
    num_labels=num,
    use_cuda=False,
    args={"reprocess_input_data": True, "overwrite_output_dir": True, "num_train_epochs": 3},
)

INFO:filelock:Lock 140260895569568 acquired on /root/.cache/torch/transformers/b945b69218e98b3e2c95acf911789741307dec43c698d35fad11c1ae28bda352.9da767be51e1327499df13488672789394e2ca38b877837e52618a67d7002391.lock


INFO:filelock:Lock 140260895569568 released on /root/.cache/torch/transformers/b945b69218e98b3e2c95acf911789741307dec43c698d35fad11c1ae28bda352.9da767be51e1327499df13488672789394e2ca38b877837e52618a67d7002391.lock


INFO:filelock:Lock 140260895482208 acquired on /root/.cache/torch/transformers/d8f11f061e407be64c4d5d7867ee61d1465263e24085cfa26abf183fdc830569.3fadbea36527ae472139fe84cddaa65454d7429f12d543d80bfc3ad70de55ac2.lock


INFO:filelock:Lock 140260895482208 released on /root/.cache/torch/transformers/d8f11f061e407be64c4d5d7867ee61d1465263e24085cfa26abf183fdc830569.3fadbea36527ae472139fe84cddaa65454d7429f12d543d80bfc3ad70de55ac2.lock


INFO:filelock:Lock 140260895569680 acquired on /root/.cache/torch/transformers/5e8a2b4893d13790ed4150ca1906be5f7a03d6c4ddf62296c383f6db42814db2.e13dbb970cb325137104fb2e5f36fe865f27746c6b526f6352861b1980eb80b1.lock


INFO:filelock:Lock 140260895569680 released on /root/.cache/torch/transformers/5e8a2b4893d13790ed4150ca1906be5f7a03d6c4ddf62296c383f6db42814db2.e13dbb970cb325137104fb2e5f36fe865f27746c6b526f6352861b1980eb80b1.lock


In [16]:
import numpy as np
print(y_train[0])
print(type(y_train))
import sklearn.preprocessing
a = y_train
print(a[0],a[1])
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y1 = le.fit_transform(a)
print(y1[0],y1[1])
label_binarizer = sklearn.preprocessing.LabelBinarizer()
label_binarizer.fit(range(max(y1)+1))
print(num)
b = label_binarizer.transform(y1)

print(b[0],b[1])
print(len(b[0]))
print(b.shape)
print(type(b))

['greedy']
<class 'numpy.ndarray'>
['greedy'] ['greedy']
12 12
23
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
23
(4000, 23)
<class 'numpy.ndarray'>


In [17]:
# print(type('Example sentence 1 for multilabel classification.', [1, 1, 1, 1, 0, 1]))
# b1=list(b)
print(type(X_train))
print(type(b))
# X_train.tolist()
b.tolist()
print(type(b[0]))
l=[]
import re
pattern = re.compile(r'\s+') 

for i in range(len(X_train)):
  l.append([re.sub(pattern, '',X_train[i]),b[i].tolist()])
# print(l[0])
train_df=pd.DataFrame(l)
model.train_model(train_df)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:251: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."
INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.


Running loss: 0.390284

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:224: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


Running loss: 0.016707


Running loss: 0.029155


Running loss: 0.017304



INFO:simpletransformers.classification.classification_model: Training of bert model complete. Saved to outputs/.


In [18]:
l=[]
a = y_test
# print(a[0],a[1])
from sklearn.preprocessing import LabelEncoder

y1 = le.fit_transform(a)
print(y1[0],y1[1])
# label_binarizer = sklearn.preprocessing.LabelBinarizer()
label_binarizer.fit(range(max(y1)+1))
print(num)
b = label_binarizer.transform(y1)
for i in range(len(X_test)):
  l.append([re.sub(pattern, '',X_test[i]),b[i].tolist()])
# print(l[0])
eval_df=pd.DataFrame(l)

22 22
23


In [19]:
result, model_outputs, wrong_predictions = model.eval_model(eval_df)
print(result)
print(model_outputs)


/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:668: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."



{'LRAP': 0.9949138888888889, 'eval_loss': 0.013017099667340517}
[[0.00427463 0.0044806  0.0046539  ... 0.00328724 0.00495155 0.98131585]
 [0.00427463 0.0044806  0.0046539  ... 0.00328724 0.00495155 0.98131585]
 [0.00427463 0.0044806  0.0046539  ... 0.00328724 0.00495155 0.98131585]
 ...
 [0.01540574 0.01313006 0.01173321 ... 0.01209445 0.00851402 0.03289828]
 [0.01057752 0.01243434 0.0101204  ... 0.01262422 0.01006221 0.02458155]
 [0.00427463 0.0044806  0.00465389 ... 0.00328724 0.00495155 0.98131585]]


In [20]:
predictions, raw_outputs = model.predict(['''
Chef Ciel is playing a game with one of her colleagues.In this game, there are k piles of numbers. There are ni numbers in ith pile. In each move, player has to select a pile and finally a number from that pile. After that, all the numbers which are greater than or equal to chosen number will be removed from that pile. Players take turn alternatively. Player who is unable to move loses the game. 
Chef Ciel always make first move. But before making her move, she must choose either EVEN or ODD. If she chooses even then each time she selects a number it must be even and her opponent must select odd number in his/her turn. And vice versa for the other case. 
Please help Chef Ciel to make her choice. If neither choice can make her win game, print DONT PLAY otherwise EVEN or ODD depending on which choice she should make to win game. If you think then you will understand BOTH can not be answer.
Assume that both players play intelligently, if they can force win they will. 
 Input :  First line of test case contains t, number of test cases. Then t test cases follow. First line of each test case contains k, number of piles.  Then description of k piles follow. ith pile description contains number ni, then ni numbers follow in the same line.
Output :  Print EVEN, ODD or DONT PLAY accordingly.
Constraints :  t <= 1000, k <=100, ni <= 45. Numbers in pile will be non-negative and less than 2^31.
Sample Input :
2
2 
2 3 4
2 4 5
1
3 1 2 3
Sample Output :
DONT PLAY ODD
Explanation: 
In the first test case, if you have chosen ODD to play with, it means you will select only ODD numbers and your opponent may choose only EVEN numbers. So you have two options. Either select 3 from first pile or 5 from second pile. If 3 is selected, 3 and 4 are removed from first pile and in next move your opponents only move will be 4 from second pile removing every numbers thus you lose. If you had selected 5, then your opponents optimal move would be selecting 4 from first pile. Next you will select 3 and your opponent 4 leaving nothing for you. So if you choose ODD you will lose. Similarly if you choose EVEN you will lose as well. So the answer is DONT Play.
In the second case, if you choose ODD just select 1 and you will win. If you choose EVEN you have only one move that is 2, and in response your opponent will choose 1 and leave you nothing. Thus answer is ODD.'''])

INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.


In [21]:
# print(predictions)
print(raw_outputs)
y=label_binarizer.inverse_transform( raw_outputs, threshold=None)
y2=le.inverse_transform(y)
print(y2)
# list(LabelEncoder().inverse_transform([y1]))

[[0.02067593 0.01097003 0.01263929 0.02122126 0.005213   0.00869423
  0.00414471 0.00514094 0.0060726  0.00604821 0.00701485 0.00535254
  0.01593917 0.00377329 0.00374112 0.00998729 0.04784172 0.00285191
  0.00439537 0.01346858 0.00611645 0.00490616 0.02073225]]
["['implementation']"]


In [0]:
# print(max(raw_outputs[0]))