In [1]:
!pip install transformers

     |████████████████████████████████| 645kB 2.7MB/s 
     |████████████████████████████████| 1.1MB 13.2MB/s 
     |████████████████████████████████| 3.8MB 16.4MB/s 
     |████████████████████████████████| 890kB 37.3MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=a86cd908d70d4f21f745a4b566e43ba48e7524c4e633336faad09fdd81b6d9b7
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [2]:
!pip install tensorboardx

     |████████████████████████████████| 204kB 2.9MB/s 


In [3]:
!pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 127.2MB 83kB/s 
     |████████████████████████████████| 5.4MB 19.3MB/s 
  Found existing installation: torch 1.5.0+cu101
    Uninstalling torch-1.5.0+cu101:
      Successfully uninstalled torch-1.5.0+cu101
  Found existing installation: torchvision 0.6.0+cu101
    Uninstalling torchvision-0.6.0+cu101:
      Successfully uninstalled torchvision-0.6.0+cu101


In [4]:
!pip install simpletransformers

     |████████████████████████████████| 194kB 2.8MB/s 
  Created wheel for seqeval: filename=seqeval-0.0.12-cp36-none-any.whl size=7424 sha256=fd9ee1f8cbcef71bba4915fd509580d4b346591e527ee1e6d5c7a5a94b06d5d6
  Stored in directory: /root/.cache/pip/wheels/4f/32/0a/df3b340a82583566975377d65e724895b3fad101a3fb729f68
Successfully built seqeval


In [0]:
from simpletransformers.classification import MultiLabelClassificationModel
import pandas as pd
import logging

In [0]:
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

In [0]:
import os
import collections
import pandas as pd

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
data=pd.read_csv("/content/drive/My Drive/data/questions.csv",usecols=[3,5,6]) 
data=data[:5000]

if len(str(data['Problem Statement']).split(".",1))>1:
  data['Problem Statement']=data['Problem Statement'].str.split(".",1).str[1]

In [10]:
data['prob_sol'] = data['Problem Statement'] +' '+ data['Solution']
data.head()

INFO:numexpr.utils:NumExpr defaulting to 2 threads.


Problem Statement  ...                                           prob_sol
0   Read problems statements in  Mandarin Chinese...  ...   Read problems statements in  Mandarin Chinese...
1   Read problems statements in  Mandarin Chinese...  ...   Read problems statements in  Mandarin Chinese...
2   Read problems statements in  Mandarin Chinese...  ...   Read problems statements in  Mandarin Chinese...
3   Read problems statements in  Mandarin Chinese...  ...   Read problems statements in  Mandarin Chinese...
4   Read problems statements in  Mandarin Chinese...  ...   Read problems statements in  Mandarin Chinese...

[5 rows x 4 columns]

In [11]:
data.head()
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop = stopwords.words('english')
# data['Problem Statement'].apply(lambda x: [item for item in x if item not in stop])
# print("done1")
# data['Solution'].apply(lambda x: [item for item in x if item not in stop])
# print("done2")
data['prob_sol'].apply(lambda x: [item for item in x if item not in stop])
print("done3")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
done3


In [0]:
unique_labels=data.tags.unique()
num=len(unique_labels)

In [13]:
# from sklearn.preprocessing import LabelEncoder
# y=data['tags']
# data["tags"] = LabelEncoder().fit_transform(y)
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
data['tags'].head()
print(type(data['tags'][0]))
# mlb.fit_transform(data['tags'])

<class 'str'>


In [0]:
from simpletransformers.classification import MultiLabelClassificationModel
import pandas as pd

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data["prob_sol"].values, data["tags"].values, test_size=0.2, random_state=42)

In [16]:
model = MultiLabelClassificationModel(
    "roberta",
    "roberta-base",
    num_labels=num,
    use_cuda=False,
    args={"reprocess_input_data": True, "overwrite_output_dir": True, "num_train_epochs": 1},
)

INFO:filelock:Lock 140034267354448 acquired on /root/.cache/torch/transformers/e1a2a406b5a05063c31f4dfdee7608986ba7c6393f7f79db5e69dcd197208534.117c81977c5979de8c088352e74ec6e70f5c66096c28b61d3c50101609b39690.lock


INFO:filelock:Lock 140034267354448 released on /root/.cache/torch/transformers/e1a2a406b5a05063c31f4dfdee7608986ba7c6393f7f79db5e69dcd197208534.117c81977c5979de8c088352e74ec6e70f5c66096c28b61d3c50101609b39690.lock


INFO:filelock:Lock 140034267354448 acquired on /root/.cache/torch/transformers/80b4a484eddeb259bec2f06a6f2f05d90934111628e0e1c09a33bd4a121358e1.49b88ba7ec2c26a7558dda98ca3884c3b80fa31cf43a1b1f23aef3ff81ba344e.lock


INFO:filelock:Lock 140034267354448 released on /root/.cache/torch/transformers/80b4a484eddeb259bec2f06a6f2f05d90934111628e0e1c09a33bd4a121358e1.49b88ba7ec2c26a7558dda98ca3884c3b80fa31cf43a1b1f23aef3ff81ba344e.lock


INFO:filelock:Lock 140034267354840 acquired on /root/.cache/torch/transformers/d0c5776499adc1ded22493fae699da0971c1ee4c2587111707a4d177d20257a2.ef00af9e673c7160b4d41cfda1f48c5f4cba57d5142754525572a846a1ab1b9b.lock


INFO:filelock:Lock 140034267354840 released on /root/.cache/torch/transformers/d0c5776499adc1ded22493fae699da0971c1ee4c2587111707a4d177d20257a2.ef00af9e673c7160b4d41cfda1f48c5f4cba57d5142754525572a846a1ab1b9b.lock


INFO:filelock:Lock 140034266390712 acquired on /root/.cache/torch/transformers/b35e7cd126cd4229a746b5d5c29a749e8e84438b14bcdb575950584fe33207e8.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda.lock


INFO:filelock:Lock 140034266390712 released on /root/.cache/torch/transformers/b35e7cd126cd4229a746b5d5c29a749e8e84438b14bcdb575950584fe33207e8.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda.lock


In [17]:
import numpy as np
# print(y_train[0])
# print(type(y_train))
import sklearn.preprocessing
a = y_train
print(a[0],a[1])
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y1 = le.fit_transform(a)
print(y1[0],y1[1])
label_binarizer = sklearn.preprocessing.LabelBinarizer()
label_binarizer.fit(range(max(y1)+1))
print(num)
b = label_binarizer.transform(y1)

# print(b[0],b[1])
# print(len(b[0]))
# print(b.shape)
# print(type(b))
# y_train=y_train.values()
# y_train = y_train.apply(lambda x :[value for value in eval(x).values()])
# print(type(df['tags'][0]))
# mlb =  MultiLabelBinarizer()
# mlb.fit_transform(y_train)
# print(y_train[0])
# print(type(y_train))
# # y_train1=np.array([x.split(',') for x in y_train])
# b=mlb.fit_transform(y_train)
print(b[0])


['greedy'] ['greedy']
12 12
23
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [0]:
# print(type(X_train))

In [19]:

print(type(X_train))
print(type(b))
# X_train.tolist()
b.tolist()
print(type(b[0]))
l=[]
import re
pattern = re.compile(r'\s+') 
# b=b.tolist()
for i in range(len(X_train)):
  l.append([X_train[i],b[i]])
# print(l[0])
train_df=pd.DataFrame(l)
print(train_df.head())


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
                                                   0                                                  1
0   Read problems statements in Mandarin Chinese ...  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...
1   Read problems statements in Mandarin Chinese ...  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...
2  \nChef likes numbers and number theory, we all...  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...
3   Read problems statements in Mandarin Chinese ...  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...
4   Read problems statements in Mandarin Chinese ...  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...


In [20]:
model.train_model(train_df)

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:251: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."
INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.


Running loss: 0.158327

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:224: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


Running loss: 0.023937



INFO:simpletransformers.classification.classification_model: Training of roberta model complete. Saved to outputs/.


In [0]:

l=[]
a = y_test
# # print(a[0],a[1])
# from sklearn.preprocessing import LabelEncoder

y1 = le.fit_transform(a)
# print(y1[0],y1[1])
# label_binarizer = sklearn.preprocessing.LabelBinarizer()
label_binarizer.fit(range(max(y1)+1))
# print(num)
b = label_binarizer.transform(y1)
b.tolist()
for i in range(len(X_test)):
  l.append([re.sub(pattern, '',X_test[i]),b[i]])
# print(l[0])
eval_df=pd.DataFrame(l)


In [22]:
result, model_outputs, wrong_predictions = model.eval_model(eval_df)
print(result)
print(model_outputs)


/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:668: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."



{'LRAP': 0.7356621573114374, 'eval_loss': 0.09279371455311775}
[[0.05402516 0.02460375 0.04311387 ... 0.02512929 0.02470255 0.09359895]
 [0.05402516 0.02460375 0.04311387 ... 0.02512929 0.02470255 0.09359895]
 [0.05402516 0.02460375 0.04311387 ... 0.02512929 0.02470255 0.09359895]
 ...
 [0.04666849 0.02067396 0.043871   ... 0.03425805 0.02592307 0.03794173]
 [0.04040507 0.02663264 0.04459138 ... 0.0270835  0.02875735 0.04457667]
 [0.05402515 0.02460376 0.04311389 ... 0.02512929 0.02470255 0.09359896]]


In [23]:
predictions, raw_outputs = model.predict(['''
Chef Ciel is playing a game with one of her colleagues.
 In this game, there are k piles of numbers. There are ni numbers in ith pile. In each move, player has to select a pile and finally a number from that pile. After that, all the numbers which are greater than or equal to chosen number will be removed from that pile. Players take turn alternatively. Player who is unable to move loses the game. 
Chef Ciel always make first move. But before making her move, she must choose either EVEN or ODD. If she chooses even then each time she selects a number it must be even and her opponent must select odd number in his/her turn. And vice versa for the other case. 
Please help Chef Ciel to make her choice. If neither choice can make her win game, print DONT PLAY otherwise EVEN or ODD depending on which choice she should make to win game. If you think then you will understand BOTH can not be answer.
Assume that both players play intelligently, if they can force win they will. 
 Input :  First line of test case contains t, number of test cases. Then t test cases follow. First line of each test case contains k, number of piles.  Then description of k piles follow. ith pile description contains number ni, then ni numbers follow in the same line.
Output :  Print EVEN, ODD or DONT PLAY accordingly.
Constraints :  t <= 1000, k <=100, ni <= 45. Numbers in pile will be non-negative and less than 2^31.
Sample Input :
2
2 
2 3 4
2 4 5
1
3 1 2 3
Sample Output :
DONT PLAY ODD
Explanation: 
In the first test case, if you have chosen ODD to play with, it means you will select only ODD numbers and your opponent may choose only EVEN numbers. So you have two options. Either select 3 from first pile or 5 from second pile. If 3 is selected, 3 and 4 are removed from first pile and in next move your opponents only move will be 4 from second pile removing every numbers thus you lose. If you had selected 5, then your opponents optimal move would be selecting 4 from first pile. Next you will select 3 and your opponent 4 leaving nothing for you. So if you choose ODD you will lose. Similarly if you choose EVEN you will lose as well. So the answer is DONT Play.
In the second case, if you choose ODD just select 1 and you will win. If you choose EVEN you have only one move that is 2, and in response your opponent will choose 1 and leave you nothing. Thus answer is ODD.'''])

INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.


In [24]:
print(raw_outputs)

[[0.03451826 0.02965201 0.02884426 0.06176989 0.03093923 0.04727114
  0.02737688 0.04389392 0.73200047 0.0322186  0.03620447 0.02680944
  0.0789615  0.02107776 0.02654821 0.04759115 0.04467595 0.02756621
  0.03650765 0.04644649 0.03390134 0.0488757  0.07342655]]


In [25]:
print(predictions)
print(raw_outputs)
y=label_binarizer.inverse_transform( raw_outputs)
y2=le.inverse_transform(y)
print(y2)
# list(LabelEncoder().inverse_transform([y1]))

[[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
[[0.03451826 0.02965201 0.02884426 0.06176989 0.03093923 0.04727114
  0.02737688 0.04389392 0.73200047 0.0322186  0.03620447 0.02680944
  0.0789615  0.02107776 0.02654821 0.04759115 0.04467595 0.02756621
  0.03650765 0.04644649 0.03390134 0.0488757  0.07342655]]
["['game']"]
